apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  namespace: development
  labels:
    app: green-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: green-app
  template:
    metadata:
      labels:
        app: green-app
    spec:
      containers:
      - name: green-container
        image: green-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: ENV_VAR
          value: "value"  # Example of environment variables
