apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: isito-gateway
  namespace: development
spec:
  selector:
    istio: ingress  # Use Istio's ingress gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - "*"
  
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: entrypoint
  namespace: development
spec:
  hosts:
    - "*"
  gateways:
    - isito-gateway
  http:
  - match:
    - uri:
        prefix: /docs
    - uri:
        prefix: /openapi.json
    - uri:
        prefix: /example
    route:
      - destination:
          host: docs-service
          port:
            number: 8000
  - match:
    - uri:
        regex: /red(/|$)(.*)
    rewrite:
      uriRegexRewrite:
        match: /red(/|$)(.*)
        rewrite: /\2
    route:
      - destination:
          host: red-service
          port:
            number: 8000
  - match:
    - uri:
        regex: /green(/|$)(.*)
    rewrite:
      uriRegexRewrite:
        match: /green(/|$)(.*)
        rewrite: /\2
    route:
      - destination:
          host: green-service
          port:
            number: 8000

  