apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: "2021-12-23T08:43:25Z"
  name: php-apache
  namespace: default
  resourceVersion: "698967"
  uid: ca30e4e2-6c55-436e-b321-903cb868eedb
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  targetCPUUtilizationPercentage: 50
status:
  currentReplicas: 0
  desiredReplicas: 0
