apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqls.db.example.com
spec:
  group: db.example.com
  version: v1
  scope: Namespaced
  names:
    plural: mysqls
    singular: mysql
    kind: Mysql
    shortNames:
      - ms
