kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: office
  name: pod-manager
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["pods", "replicasets", "deployments", "events", "serviceaccounts", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] # You can also use ["*"]
