kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-manager-binding
  namespace: office
subjects:
- kind: User
  name: employee
  apiGroup: ""
- kind: ServiceAccount
  name: default
  namespace: office
roleRef:
  kind: Role
  name: pod-manager
  apiGroup: ""
