apiVersion: apps/v1
kind: Deployment
metadata:
  name: visitors-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visitors
      tier: backend
  template:
    metadata:
      labels:
        app: visitors
        tier: backend
    spec:
      containers:
        - name: visitors-backend
          image: "jdob/visitors-service:1.0.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: visitors
              containerPort: 8000
          env:
            - name: MYSQ_DATABASE
              value: visitors_db
            - name: MYSQ_SERVICE_HOST
              value: mysql-service
            - name: MYSQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-auth
                  key: username
            - name: MYSQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-auth
                  key: password
